# Assignment

Import numpy as np

In [1]:
import numpy as np

Make a python list => \[1,2,3,4,5\]

Convert it into numpy array and print it

In [2]:
list1 = [1,2,3,4,5]
list1_np = np.array(list1)
print(list1_np)

[1 2 3 4 5]


Make a python matrix (3 x 3) => \[[1,2,3],[4,5,6],[7,8,9]\]

Convert it into numpy array and print it

In [3]:
matrix = [[1,2,3],[4,5,6],[7,8,9]]
matrix_np = np.array(matrix)
print(matrix_np)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Make a matrix (3 x 3) using built-in methods (like arange(), reshape() etc.):

\[ [1,3,5],

 [7,9,11],
 
 [13,15,17] \]

In [4]:
matrix1 = np.arange(1,18,2)
matrix1 = matrix1.reshape(3,3)
print(matrix1)

[[ 1  3  5]
 [ 7  9 11]
 [13 15 17]]


Create a numpy array with 10 random numbers from 0 to 10 (there should be few numbers greater than 1)

In [5]:
random_array = np.random.randint(0,10,10)
print(random_array)

[9 2 1 2 0 5 7 1 9 1]


Create numpy array => \[1,2,3,4,5\] and convert it to 2D array with 5 rows

In [6]:
np_array = np.array([1,2,3,4,5])
np_array = np_array.reshape(5,)
print(np_array)

[1 2 3 4 5]
(5,)


Print the shape of the above created array

In [7]:
print(np_array.shape)

(5,)


Create a numpy array with 10 elements in it. Access and print its 3rd, 4th and 9th element.

In [16]:
npy_array = np.array([0,50,10,54,7,3,87,45,89,34])
print("3rd element : ",npy_array[2])
print("4th element : ",npy_array[3])
print("9th element : ",npy_array[8])

3rd element :  10
4th element :  54
9th element :  89


Print alternate elements of that array

In [43]:
i=0
for i in range(len(npy_array)):
    if i%2 == 0:
        print(npy_array[i])

0
10
7
87
100


Change last 3 elements into 100 using broadcasting and print

In [17]:
npy_array[7:] = 100
print(npy_array)

[  0  50  10  54   7   3  87 100 100 100]


Create a 5 x 5 matrix (fill it with any element you like), print it.

Then print the middle (3 x 3) matrix.

In [21]:
npy_matrix = np.arange(0,25).reshape(5,5)
print(npy_matrix)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [47]:
print(npy_matrix[1:4,1:4])

[[ 6  7  8]
 [11 12 13]
 [16 17 18]]
